GUI_TARGET = manager
CLI_TARGET = eps_builder

GUI_SRC = manager.c
CLI_SRC = eps_builder.c

CFLAGS = -DUNICODE -D_UNICODE
LDFLAGS = -lcore -lutils -lgdiplus -lole32 -luuid

include ../../make_template